src/Entity/Appointment.php
<?php

namespace App\Entity;

use App\Repository\AppointmentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AppointmentRepository::class)]
class Appointment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    private int $idap;

    #[ORM\Column(type: "date")]
    private \DateTimeInterface $dateap;

    #[ORM\Column(type: "string", length: 5)]
    private string $hour;

    #[ORM\Column(type: "boolean")]
    private bool $status=false;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: "idMedecin", referencedColumnName: "iduser")]
    private ?User $idmedecin ;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: "idPatient", referencedColumnName: "iduser")]
    private ?User $idpatient;
   

    public function getIdap(): int
    {
        return $this->idap;
    }

    public function getDateap(): \DateTimeInterface
    {
        return $this->dateap;
    }

    public function setDateap(\DateTimeInterface $dateap): self
    {
        $this->dateap = $dateap;
        return $this;
    }

    public function getHour(): string
    {
        return $this->hour;
    }

    public function setHour(string $hour): self
    {
        $this->hour = $hour;
        return $this;
    }

    public function isStatus(): bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;
        return $this;
    }

    public function getIdmedecin(): ?User
    {
        return $this->idmedecin;
    }

    public function setIdmedecin(?User $idmedecin): self
    {
        $this->idmedecin = $idmedecin;
        return $this;
    }

    public function getIdpatient(): ?User
    {
        return $this->idpatient;
    }

    public function setIdpatient(?User $idpatient): self
    {
        $this->idpatient = $idpatient;
        return $this;
    }

    public function getIdmedecinId(): ?int
{
    return $this->idmedecin ? $this->idmedecin->getIduser() : null;
}

public function getIdpatientId(): ?int
{
    return $this->idpatient ? $this->idpatient->getIduser() : null;
}

public function getMedecinName(): ?string
{
    return $this->idmedecin ? $this->idmedecin->getFirstname() . ' ' . $this->idmedecin->getLastname() : null;
}
public function getPatientName(): ?string
{
    return $this->idpatient ? $this->idpatient->getFirstname() . ' ' . $this->idpatient->getLastname() : null;
}
   

}

src/Form/AppointmentType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;
use Symfony\Component\Validator\Constraints\GreaterThan;

use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use DateTime;

class AppointmentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('dateap', null, [
            'constraints' => [
                new NotBlank([
                    'message' => 'La date est obligatoire'
                ]),
               
                new GreaterThan([
                    'value' => 'today',
                    'message' => 'La date doit être supérieure à la date actuelle'
                ]),
            ]
        ])
        ->add('hour', null, [
            'constraints' => [
                new NotBlank([
                    'message' => 'L\'heure est obligatoire'
                ]),
            ]
        ])
        ->add('ajouter', SubmitType::class)
    ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/AppointmentController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Appointment;
use App\Entity\User;
use App\Form\AppointmentType; // Ajout de cette ligne
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\AppointmentRepository;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use App\Form\AppointmentSearchType; // Ajout de cette ligne
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;




use App\Services\MailService;


class AppointmentController extends AbstractController
{
    #[Route('/Appointment', name: 'app_appointment')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $appointmentRepository = $entityManager->getRepository(Appointment::class);
        $appointments = $appointmentRepository->findAll();
        $appointmentsByMonth = $appointmentRepository->countAppointmentsByMonth();
        $appointmentsByMedecin = $appointmentRepository->countAppointmentsByMedecin();
        $appointmentStatus = $appointmentRepository->countAppointmentsByStatus();
        return $this->render('appointment/index.html.twig', [
            'controller_name' => 'AppointmentController','a' => $appointments,
            'totalAppointments' => $appointmentStatus['total'],
            'confirmedAppointments' => $appointmentStatus['confirmed'],
            'waitingAppointments' => $appointmentStatus['waiting'],
        ]);
    }



    #[Route('/appointments/patient/{id}', name: 'appointments_patient')]
    public function appointmentsByPatient(AppointmentRepository $appointmentRepository, int $id): Response
    {
        $appointments = $appointmentRepository->findBy(['idpatient' => $id]);
    
        return $this->render('appointment/patient.html.twig', [
            'appointments' => $appointments
        ]);
    }


    
    #[Route('/appointments/doctor/{id}', name: 'appointments_doctor')]
public function appointmentsByDoctor(AppointmentRepository $appointmentRepository, int $id): Response
{
    $appointments = $appointmentRepository->findBy(['idmedecin' => $id]);

    return $this->render('appointment/doctor.html.twig', [
        'appointments' => $appointments
    ]);
}
    
    

    
    


    #[Route('/appointments/new/{idmedecin}/{idpatient}', name: 'appointments_new')]
public function new(Request $request, EntityManagerInterface $entityManager, int $idmedecin, int $idpatient): Response
{   
    $medecin = $entityManager->getRepository(User::class)->find($idmedecin);
    $patient = $entityManager->getRepository(User::class)->find($idpatient);

    $appointment = new Appointment();
    $appointment->setIdmedecin($medecin);
    $appointment->setIdpatient($patient);

    $form = $this->createForm(AppointmentType::class, $appointment);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $entityManager->persist($appointment);
        $entityManager->flush();
        $this->addFlash('success', 'Le rendez-vous a été ajouté avec succès.');

        return $this->redirectToRoute('appointments_patient', ['id' => 2]);
    }

    return $this->render('appointment/new.html.twig', [
        'form' => $form->createView(),
    ]);
}

#[Route('/appointments/{id}', name: 'appointments_show')]
public function show(Appointment $appointment): Response
{
    return $this->render('appointment/show.html.twig', [
        'appointment' => $appointment,
    ]);
}

#[Route('/appointments/{id}/edit', name: 'appointments_edit')]
public function edit(Request $request, Appointment $appointment, EntityManagerInterface $entityManager): Response
{
    $form = $this->createForm(AppointmentType::class, $appointment);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $entityManager->flush();
        $this->addFlash('success', 'Le rendez-vous a été modifié avec succès.');

        return $this->redirectToRoute('app_appointment');
    }

    return $this->render('appointment/edit.html.twig', [
        'appointment' => $appointment,
        'form' => $form->createView(),
    ]);
}


#[Route('/appointments/{id}/delete', name: 'appointments_delete')]
    public function delete(Request $request, Appointment $appointment, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($appointment);
        $entityManager->flush();
        $this->addFlash('success', 'Le rendez-vous a été supprimé avec succès.');

        return $this->redirectToRoute('app_appointment');
    }

   

    
    #[Route('/Appointments/search', name: 'appointments_search')]
    public function search(Request $request, AppointmentRepository $repository): Response
    {
        // Créer un formulaire de recherche de rendez-vous
        $form = $this->createForm(AppointmentSearchType::class);

        // Traitement de la soumission de formulaire
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Récupérer les données du formulaire
            $formData = $form->getData();

            // Rechercher les rendez-vous correspondant aux critères de recherche
            $appointments = $repository->findBySearchCriteria($formData);
        } else {
            // Si le formulaire n'a pas été soumis ou s'il n'est pas valide,
            // initialiser la variable $appointments à une tableau vide
            $appointments = [];
        }

        // Ajouter la condition pour filtrer selon le statut confirmé ou non confirmé
        if (isset($formData['status'])) {
            if ($formData['status'] === true) {
                $appointments = array_filter($appointments, function ($appointment) {
                    $appointment->setStatus(true);
                    return $appointment->isStatus();
                });
            } elseif ($formData['status'] === false) {
                $appointments = array_filter($appointments, function ($appointment) {
                    $appointment->setStatus(false);
                    return !$appointment->isStatus();
                });
            }
        }
        

        return $this->render('appointment/search.html.twig', [
            'form' => $form->createView(),
            'appointments' => $appointments,
        ]);
    }
    #[Route('/appointments/{id}/confirm', name: 'appointments_confirm')]
public function confirm(Request $request,MailService $mailer, Appointment $appointment, EntityManagerInterface $entityManager): Response
{
    $appointment->setStatus(true);
    $entityManager->flush();
    $context=[
        
    ];
   
    $mailer->sendEmail(
       "amenibelhadj556@gmail.com",'Email/email.html.twig',"Confirmation du RDV",$context,
        
            
    
        
        );
        

    

    
    

   

    return $this->redirectToRoute('app_appointment');
}
#[Route('/stat', name: 'stat')]
    public function stat(AppointmentRepository $appointmentRepository): Response
    {
        $appointmentsByMonth = $appointmentRepository->countAppointmentsByMonth();
        $appointmentsByMedecin = $appointmentRepository->countAppointmentsByMedecin();
        $appointmentStatus = $appointmentRepository->countAppointmentsByStatus();
    
        return $this->render('appointment/calendar.html.twig', [
            'appointmentsByMonth' => $appointmentsByMonth,
            'appointmentsByMedecin' => $appointmentsByMedecin,
            'totalAppointments' => $appointmentStatus['total'],
            'confirmedAppointments' => $appointmentStatus['confirmed'],
            'waitingAppointments' => $appointmentStatus['waiting'],
            
        ]);
    }

    #[Route('/cal', name: 'cal')]
    public function cal(AppointmentRepository $appointmentRepository): Response
    {
        $appointments = $appointmentRepository->findAll();
        $appointmentsByMonth = $appointmentRepository->countAppointmentsByMonth();
        $appointmentsByMedecin = $appointmentRepository->countAppointmentsByMedecin();
        $appointmentStatus = $appointmentRepository->countAppointmentsByStatus();
        return $this->render('appointment/cal.html.twig', [
            'controller_name' => 'AppointmentController',
            'appointments' => $appointments,
            'appointmentsByMonth' => $appointmentsByMonth,
            'appointmentsByMedecin' => $appointmentsByMedecin,
            'totalAppointments' => $appointmentStatus['total'],
            'confirmedAppointments' => $appointmentStatus['confirmed'],
            'waitingAppointments' => $appointmentStatus['waiting'],
        ]);
    }

    /**=============================================partie json =============================================================*/






  
  /**  public function indexJSON(EntityManagerInterface $entityManager, NormalizerInterface $normalizer): Response
    {
        $appointmentRepository = $entityManager->getRepository(Appointment::class);
        $appointments = $appointmentRepository->findAll();

        $jsonContent = $normalizer->normalize($appointments, 'json', ['groups' => 'appointments']);
        $response = new Response();
        $response->headers->set('Content-Type', 'application/json');
        $response->setContent(json_encode($jsonContent));

        return $response;
    }*/ 
    
    #[Route('/AppointmentJSON', name: 'app_appointmentJSON')]

templates/appointment/doctor.html.twig
{% extends 'back.html.twig' %}

{% block title %}Hello ParapharmacieController!{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Rendez-vous par médecin</h1>
                <hr>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Date</th>
                            <th>Heure</th>
                            <th>ID Patient</th>
                            <th>ID Médecin</th>
                            <th>État</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for appointment in appointments %}
                            <tr>
                                <td>{{ appointment.idap }}</td>
                                <td>{{ appointment.dateap ? appointment.dateap|date('Y-m-d') : '' }}</td>
                                <td>{{ appointment.hour|date('H:i') }}</td>
                                <td>{{ appointment.medecinName }}</td>
                                <td>{{ appointment.getPatientName() }}</td>
                                <td>
                                    {% if appointment.status == 1 %}
                                        <span class="badge badge-success">Confirmé</span>
                                    {% else %}
                                        <span class="badge badge-warning">En attente</span>
                                    {% endif %}
                                </td>
                                <td>
                {% if appointment.status == 0 %}
                <a href="{{ url('appointments_confirm', {'id': appointment.idap}) }}" class="btn btn-success" title="Confirmer le rendez-vous">
                    <i class="bi bi-check"></i>
                  </a>
                {% endif %}
                <div class="btn-group">
                  <a href="{{ path('appointments_show', {'id': appointment.idap})}}" class="btn btn-primary" title="Voir">
                    <i class="bi bi-eye"></i>
                  </a>
                  <a href="{{ path('appointments_edit', {'id': appointment.idap})}}" class="btn btn-info" title="Modifier">
                    <i class="bi bi-pencil"></i>
                  </a>
                  <a href="{{ path('appointments_delete', {'id': appointment.idap})}}" class="btn btn-danger" title="Supprimer" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce rendez-vous ?')">
                    <i class="bi bi-trash"></i>
                  </a>
                </div>
              </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/appointment/index.html.twig
{% extends 'back.html.twig' %}

{% block title %}Hello ParapharmacieController!{% endblock %}

{% block body %}

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-YnznVtMWhG2l5O5I3qC1hTpjOatDGfkhBZ+/XcZttvp8MIvzBjH+LTaUfme6zWd+v0J+tF0M7VYXpz6zg8WOvQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<style>
  .container{
    margin-top:30px;
    margin-right:50px;
  }

</style>

{% for label, messages in app.flashes %}
    {% for message in messages %}
        <div class="alert alert-{{ label }}">
            {{ message }}
        </div>
    {% endfor %}
{% endfor %}
<!-- Sale & Revenue Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-6 col-xl-3">
                        <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
                            <i class="fa fa-duotone fa-calendar-check fa-4x text-primary"></i>
                            <div class="ms-3">
                                <p class="mb-2">Total Rdv</p>
                                <h6 class="mb-0">{{ totalAppointments }}</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xl-3">
                        <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
                            <i class="fa fa-chart-bar fa-4x text-danger"></i>
                            <div class="ms-3">
                                <p class="mb-2"> RDV confirmé </p>
                                <h6 class="mb-0">{{ waitingAppointments }}</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xl-3">
                        <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
                            <i class="fa fa-chart-area fa-4x text-success"></i>
                            <div class="ms-3">
                                <p class="mb-2"> en attente</p>
                                <h6 class="mb-0">{{ confirmedAppointments }}</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xl-3">
                        <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
                            <i class="fa fa-chart-pie fa-4x text-warning"></i>
                            <div class="ms-3">
                                <p class="mb-2">Total Revenue</p>
                                <h6 class="mb-0">$1234</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Sale & Revenue End -->
<div class="container">

  <div class="row justify-content-center">
    <div class="col-md-10">

      <table class="table table-striped">
        <thead style="background-color:#1977CC;">
          <tr>
            <th>Id</th>
            <th>Date RDV</th>
            <th>Heure RDV</th>
            <th>Id patient</th>
            <th>Id médecin</th>
            <th>Etat RDV</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for appointment in a %}
            <tr>
              <td>{{ appointment.idap }}</td>
              <td>{{ appointment.dateap ? appointment.dateap|date('Y-m-d') : '' }}</td>
              <td>{{ appointment.hour|date('H:i') }}</td>
              <td>{{ appointment.medecinName }}</td>
              <td>{{ appointment.getPatientName() }}</td>
              <td>
                {% if appointment.status == 1 %}
                  <span class="badge badge-success">Confirmé</span>
                {% else %}
                  <span class="badge badge-warning">En attente</span>
                {% endif %}
              </td>

              <td>
                {% if appointment.status == 0 %}
                <a href="{{ url('appointments_confirm', {'id': appointment.idap}) }}" class="btn btn-success" title="Confirmer le rendez-vous">
                    <i class="bi bi-check"></i>
                  </a>
                {% endif %}
                <div class="btn-group">
                  <a href="{{ path('appointments_show', {'id': appointment.idap})}}" class="btn btn-primary" title="Voir">
                    <i class="bi bi-eye"></i>
                  </a>
                  <a href="{{ path('appointments_edit', {'id': appointment.idap})}}" class="btn btn-info" title="Modifier">
                    <i class="bi bi-pencil"></i>
                  </a>
                  <a href="{{ path('appointments_delete', {'id': appointment.idap})}}" class="btn btn-danger" title="Supprimer" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce rendez-vous ?')">
                    <i class="bi bi-trash"></i>
                  </a>
                </div>
              </td>
            </tr>
          {% else %}
            <tr>
              <td colspan="5">Aucun enregistrement trouvé</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% for message in app.session.flashBag.get('success') %}
    <div class="alert alert-success">{{ message }}</div>
{% endfor %}

    </div>
  </div>
</div>

{% endblock %}

templates/appointment/patient.html.twig
{% extends 'front.html.twig' %}

{% block title %}Vos rendez-vous{% endblock %}

{% block body %}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-YnznVtMWhG2l5O5I3qC1hTpjOatDGfkhBZ+/XcZttvp8MIvzBjH+LTaUfme6zWd+v0J+tF0M7VYXpz6zg8WOvQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
  <div class="container" style="margin-top: 170px;">
    <div class="row">
      {% for appointment in appointments %}
        <div class="col-md-6">
          <div class="card border-0 rounded-3 shadow-sm mb-4">
            <div class="card-header bg-light">
              <h5 class="card-title">{{ appointment.dateap|date('d/m/Y') }} - {{ appointment.hour|date('H:i') }}</h5>
            </div>
            <div class="card-body">
              <p class="card-text"><strong>Médecin :</strong> {{ appointment.medecinName }}</p>
              <p class="card-text"><strong>Spécialité :</strong> </p>
              <div class="btn-group" role="group">
                <a href="{{ path('appointments_edit', {'id': appointment.idap}) }}" class="btn btn-info mx-2" title="Modifier">edit
                  <i class="bi bi-pencil"></i>
                </a>
                <a href="{{ path('appointments_delete', {'id': appointment.idap}) }}" class="btn btn-danger" title="Supprimer">delete
                  <i class="bi bi-trash"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/appointment/search.html.twig
{% extends 'back.html.twig' %}

{% block body %}
<link href="{{ asset('admin/img/favicon.ico') }}" rel="icon">
  <div class="container">
    <h1 class="text-center mt-4 mb-5">Recherche de rendez-vous</h1>

    <div class="row justify-content-right">
      <div class="col-lg-8">
        {{ form_start(form, {'attr': {'class': 'form'}}) }}
          <div class="row">
            <div class="col-lg-4">
              <div class="form-group">
                {{ form_row(form.patientName, {'attr': {'class': 'form-control', 'placeholder': 'Nom du patient'}}) }}
              </div>
            </div>
            <div class="col-lg-4">
              <div class="form-group">
                {{ form_row(form.appointmentDate, {'attr': {'class': 'form-control', 'placeholder': 'Date du rendez-vous'}}) }}
              </div>
            </div>
            <div class="col-lg-4">
              <div class="form-group">
                {{ form_row(form.appointmentTime, {'attr': {'class': 'form-control', 'placeholder': 'Heure du rendez-vous'}}) }}
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            {{ form_row(form.search, {'attr': {'class': 'btn btn-primary'}}) }}
          </div>
        {{ form_end(form) }}
      </div>
    </div>

    {% if appointments is not empty %}
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <table class="table table-striped table-bordered mt-5">
            <thead>
              <tr>
                <th scope="col">Nom du patient</th>
                <th scope="col">Date du rendez-vous</th>
                <th scope="col">Heure du rendez-vous</th>
              </tr>
            </thead>
            <tbody>
              {% for appointment in appointments %}
                <tr>
                  <td>{{ appointment.getPatientName() }}</td>
                  <td>{{ appointment.getDateap()|date('d/m/Y') }}</td>
                  <td>{{ appointment.getHour()|date('H:i') }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    {% endif %}
  </div>

  <style>
    .container {
      max-width: 1200px;
      margin: 0 auto;
    }

    .form {
      
      background-color: #f2f2f2;
      border-radius: 10px;
      padding: 30px;
      box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
      margin: 0 auto;
      width:1000px;
     
    }

    .table {
      background-color: #fff;
      border-radius: 10px;
      box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
    }
  </style>
{% endblock %}

templates/appointment/show.html.twig
{% extends 'back.html.twig' %}





{% block body %}


<div class="container" style="margin: 0 auto; width: 50% ; margin-top: 90px; ">
    <div class="card">
        <div class="card-body text-center">
            <h5 class="card-title">Rendez-vous avec {{ appointment.medecinName }}</h5>
            <p class="card-text">Date : {{ appointment.dateAp|date('d/m/Y') }}</p>
            <p class="card-text">Heure : {{ appointment.hour|date('H:i') }}</p>          
            <p class="card-text">Patient : {{ appointment.getPatientName() }} </p>
        </div>
    </div>
</div>




{% endblock %}